#Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Home
email: killian_vuillemot@etu.u-bourgogne.fr
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://KVuillemot.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KVuillemot
github: [metadata]
# Build settings
markdown: kramdown
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache



collections:
  reminders:
    output: true
    permalink: /:collection/:path/
  teachings:
    output: true
    permalink: /:collection/:path/


# default configurations for each type
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      share: true
      author_profile: true
      classes: wide

# _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

author:
  name: "Killian Vuillemot"
  avatar: 
  bio: "Master's degree student" # Note: Markdown is allowed
  location: "Dijon, France"
  email            : "killian_vuillemot@etu.u-bourgogne.fr"
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "KVuillemot"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : 
  lastfm           :
  pinterest        :
  linkedin         : "Killian Vuillemot"
  soundcloud       :
  stackoverflow    : 
  steam            : 
  tumblr           :
  twitter          : "Killian_Vuil"
  vine             :
  weibo            :
  xing             :
  youtube          : 


# Site
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

